/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'WatanabeShogo' at '16/06/28 8:41' with Gradle 2.9
 *
 * @author WatanabeShogo, @date 16/06/28 8:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
